### ISSUE TITLE
Confusing typo in readme.md

### ISSUE THREAD

**Issue by simonvane** [oskardudycz/EventSourcing.NetCore#180]
I think there is a typo in section 1.7 of the readme.md.

I think the object type here:
```
var reservation = new ReservationId (
    reservationId,
    seatId,
    customerId
);
```
Should be `Reservation` rather than `ReservationId` i.e:
```
var reservation = new Reservation (
    reservationId,
    seatId,
    customerId
);
```

I think it is correct later on in the section i.e.
```
public class Reservation : Aggregate<ReservationId, Guid>
{
    ...
}
```

Apologies if I have misunderstood what's happening here.

Thanks.

**Comment by oskardudycz** [comment]
@simonvane, good catch! Fixed in https://github.com/oskardudycz/EventSourcing.NetCore/pull/187.
