### ISSUE TITLE
AccountSummaryViewProjection - Guid - Why ?

### ISSUE THREAD

**Issue by BienioM** [oskardudycz/EventSourcing.NetCore#2]
Why did you inside AccountSummaryViewProjection hard-code the guid ? 

> `  readonly Guid viewid = new Guid("a8c1a4ac-686d-4fb7-a64a-710bc630f471"); `

Inside **ctor** it's:

> ` ProjectEvent<NewAccountCreated>((ev)=> viewid, Persist); `

Why not ?:

> `ProjectEvent<NewAccountCreated>((ev)=> ev.AccountId, Persist);  `

??

**Comment by mabien** [comment]
When I run your code, and try to add some new accounts, only the first hit is succeed. Next try end up with exception: 

> 'EventSourcing.Sample.Tasks.Views.Accounts.AccountsSummaryView' with same Id already added to the session.'

**Comment by oskardudycz** [comment]
Yup, the sample is not finished yet, it's during refactoring. The static guid is just because Marten needs to have id (it should be probable sth like the Bank id at the end. Good catches. Will fix asap

**Comment by oskardudycz** [comment]
I fixed problem with null pointer exception. Samples were being refactored also, now they should work without errors. Added more descriptive naming (eg. AllAccountsSummary instead AccountsSummary). Problem also lied with private setters for the view properties. By default Marten require that to have proper serialization.

**Comment by oskardudycz** [comment]
@mabien I placed also another fix. Not it's not needed anymore to have inline Guid for the View Projection, where there should exist only one record. Now it's automatically done by Marten, it tries to find the existing record id - if it founds it - it uses existing one, if not (no projection has been ever made) - it will take new generated (methods ProjectSingleEventToSingleRecord and FindIdOfRecord from AccountSummaryViewProjection). 
`  public class AccountSummaryViewProjection : ViewProjection<AccountsSummaryView>
    {
        public AccountSummaryViewProjection()
        {
            ProjectEventToSingleRecord<NewAccountCreated>(Persist);    
        }

        private void Persist(AccountsSummaryView view, NewAccountCreated @event)
        {
            view.ApplyEvent(@event);
        }
        
        ViewProjection<AccountsSummaryView> ProjectEventToSingleRecord<TEvent>(Action<AccountsSummaryView, TEvent> handler) where TEvent : class
        {
            return ProjectEvent((documentSession, ev) => FindIdOfRecord(documentSession) ?? Guid.NewGuid(), handler);
        }

        Guid? FindIdOfRecord(IDocumentSession documentSession)
        {
            return documentSession.Query<AccountsSummaryView>()
                               .Select(t => (Guid?)t.Id).SingleOrDefault();
        }
    }`
You can also look on more detailed explanation in test: [ViewProjectionsTest](https://github.com/oskardudycz/EventSourcing.NetCore/blob/master/Marten.Integration.Tests/EventStore/Projections/ViewProjectionsTest.cs)

**Comment by BienioM** [comment]
Works :smiley:
