### ISSUE TITLE
docker-compose up doens't work in the main folder

### ISSUE THREAD

**Issue by faysou** [oskardudycz/EventSourcing.NetCore#33]
Building the sample project in docker doesn't work using the latest version that uses .Net 5. There are some version issues in the DOCKERFILE file.

It builds using the commit of the 31st of october.

I get this error though:
event_sourcing_sample | Application startup exception: System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered.

In all cases, thank you for your great work

**Comment by oskardudycz** [comment]
Hey @faysou, thank you for the feedback - good catch! 

See #35:
- Fixed Dockerfile - added proper multistage build and replaced sample from Bank Accounts to Cinema Tickets (as it's more complete)
- Added pgAdmin image to docker-compose to be able to see changes in DB
- Added .dockerignore to not copy binaries into the docker build
- Added missing projects to Tickets/Tickets.sln
- Updated README information about .NET
- Configured docker build github action
