### ISSUE TITLE
Some bugs to fix and a question

### ISSUE THREAD

**Issue by faysou** [oskardudycz/EventSourcing.NetCore#36]
Thank you for your previous update to my previous request.
I'm trying to run some of the demos and there are a few things to correct in some of the files.

1) There is a problem in all projects in the current commit, the marten package has two versions, one being unavailable (the 5.0 one).
    \<PackageReference Include="Marten" Version="4.0.0-alpha.4" />
    \<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    \<PackageReference Include="Marten" Version="5.0.0" />

2) There is a problem with ElasticSearch when running this docker file.
https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Workshops/BuildYourOwnEventStore/02-EventSourcingAdvanced/docker/docker-compose.yml

I get the following errors,
{"type":"log","@timestamp":"2021-01-03T18:29:14Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1           | {"type":"log","@timestamp":"2021-01-03T18:29:18Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}

I managed to solve them by using the elasticsearch and kibana docker specifications from this url
https://medium.com/@TimvanBaarsen/how-to-run-an-elasticsearch-7-x-single-node-cluster-for-local-development-using-docker-compose-2b7ab73d8b82

3) Related to the same docker file, I get this error when the MettingsManagement.Api and MeetingsSearch.Api projects try to connect to Kafka.

%3|1609698927.479|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Failed to resolve 'kafka:9092': No such host is known.  (after 2287ms in state CONNECT)

I managed to solve them by changing this line in the docker file :
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 (localhost instead of kafka)

I used this post to solve the error
https://stackoverflow.com/questions/52438822/docker-kafka-w-python-consumer/52440056

4) Finally I have a question, I'm not sure if the messages are flowing to elasticsearch in the MeetingsSearch.Api project, the MeetingSearch api requires a filter to query in swager, and I don't know which format to use for this filter.
When I connect to Kibana, I don't find any data stored in eleasticsearch, which should be the case if the view creation was working.

Would it be possible that you check if the project is working and give a query example after a meeting and its schedule are created? I think it's a great example to understand your ideas and I would be very happy to get it to work.

Thank you for your work

**Comment by faysou** [comment]
I think I've found an important bug regarding IExternalEventProducer.

This line needs to be commented
https://github.com/oskardudycz/EventSourcing.NetCore/blob/0217ff3dffdbd384b560165da6ca2b2e6c1d8c87/Core/Config.cs#L21

So this line can work
https://github.com/oskardudycz/EventSourcing.NetCore/blob/ba04e5ae2cac0a7601da4ce77dfab192e02cb5bf/Core.Streaming.Kafka/Config.cs#L15

I don't know if there's a better way than commenting the line that fits your code better, I don't have much experience in C# in order to know what is better.

**Comment by faysou** [comment]
After the fix of the previous comment I had to change this line to add a kafka producer as well.

https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Workshops/BuildYourOwnEventStore/02-EventSourcingAdvanced/MeetingsSearch.Api/Startup.cs#L31

**Comment by faysou** [comment]
I've modified instead this function like this

        public static IServiceCollection AddKafkaProducer(this IServiceCollection services)
        {
            var serviceDescriptor = services.FirstOrDefault(descriptor => descriptor.ServiceType == typeof(IExternalEventProducer));
            services.Remove(serviceDescriptor);

            //using TryAdd to support mocking, without that it won't be possible to override in tests
            services.TryAddScoped<IExternalEventProducer, KafkaProducer>();
            return services;
        }

**Comment by oskardudycz** [comment]
@faysou, I apologise for the late answer. I've recently done a massive revamp of those samples. If it's not working, I'll reopen the issue. Could you try again?
