### ISSUE TITLE
What architecture do you use for your sample projects?

### ISSUE THREAD

**Issue by mehdihadeli** [oskardudycz/EventSourcing.NetCore#47]
Hi @oskardudycz,
What architecture do you use for your samples in this project? Is it jimmy bogard vertical slice architecture?

**Comment by oskardudycz** [comment]
@mehdihadeli, this architecture is made based on my personal experience and understanding of the CQRS and Event Sourcing pattern. 
For sure, it has the same assumptions and goals for slicing, and also, the majority of samples are using MediatR. Still, probably @jbogard would need to say if it's a valid implementation or not. 😄 

I'm trying to cut the number of horizontal layers, keep things explicit and as simple as possible. A lot of stuff is derived from the DDD (like, e.g. only exposing what you have to, aggregate pattern etc.).

I'm not sure if that answers your question. If not, feel free to drill down 😃

**Comment by mehdihadeli** [comment]
@oskardudycz Thanks Oskar for your explanation, It seems great like always 😃. I use kamil implementation in my architecture, and it is also clean, actually it is a mix of vertical slice and feature folder 
- [Feature Folders](http://www.kamilgrzybek.com/design/feature-folders/)
- [https://github.com/kgrzybek/modular-monolith-with-ddd](https://github.com/kgrzybek/modular-monolith-with-ddd)

**Comment by oskardudycz** [comment]
@mehdihadeli, thank you for the feedback. Kamil is doing a great job with his Modular Monolith. I also like it. After my latest example of simple CQRS, I'll also migrate the rest of the samples to use folders per business operation (command/query). So, in general it will look like this:

- Aggregate/Submodule - e.g. Products
    - Command - RegisterProduct
    - Query - GetProductDetails
    - etc.
    
I think that it'll help to keep the stuff that changes together in the same place. I'm also considering keeping commands in the same file as handler etc.

Thoughts?

**Comment by mehdihadeli** [comment]
Yes, it is ok, Good approach :)
