### ISSUE TITLE
Core.Marten.Repository.MartenRepository.Delete does not delete.

### ISSUE THREAD

**Issue by soernt** [oskardudycz/EventSourcing.NetCore#79]
Hi there,

the implementation calls the private Store function, which is implemented as:
```        private async Task Store(T aggregate, CancellationToken cancellationToken)
        {
            var events = aggregate.DequeueUncommittedEvents();
            documentSession.Events.Append(
                aggregate.Id,
                events
            );
            await documentSession.SaveChangesAsync(cancellationToken);
            await eventBus.Publish(events);
        }
```

**Comment by NikiforovAll** [comment]
I guess this is intentional, probably you want to add EntityDeleted event and implement soft delete filtering on the read side.

Also, you may want to use something like: https://martendb.io/events/archiving.html

NB: I'm not a library author, just stumbled on a similar question

**Comment by soernt** [comment]
I ended up using the archiving after calling store, just in case there are some events that needs to be published.

**Comment by oskardudycz** [comment]
@soernt, as @NikiforovAll described, in Event Sourcing, delete is just a separate event. That's also similar to real-life: when you put something to trashbin, it doesn't disappear, just changing location 😉 

Having that deleted is usually a business operation that should be interpreted by subscribers or read model. E.g. cancelling a reservation, confirming a shopping basket, etc. All of those events are "freezing" the lifetime of the object. Whether it means deletion or not is a matter of interpretation. Also, requirements may change, and you may then want to "unfreeze" those objects.

One of the Event Sourcing superpowers lies in not-losing business information. If you try to immediately archive stream or delete events immediately, you may lose some of the information. Also, archiving streams won't notify subscribers. It is only local change. Also, technically if you archive stream, you may not be able to rebuild projections or republish events if you want to fix the read models.

Archivisation is an essential process and feature, but it should always be considered case by case. Discussion with business on the lifetime is a must. After defining the strategy, we should do archivisation. 

I'd recommend still storing and publishing events on delete operation, then using Async Daemon (or another type of subscription) based on defined strategy archive streams asynchronously, e.g. listening for the "delete" event.

**Comment by soernt** [comment]
Thank you for the detailed explanation!
When I have a look at the repository interface: 

```
    public interface IRepository<T> where T : IAggregate
    {
        Task<T?> Find(Guid id, CancellationToken cancellationToken);

        Task Add(T aggregate, CancellationToken cancellationToken);

        Task Update(T aggregate, CancellationToken cancellationToken);

        Task Delete(T aggregate, CancellationToken cancellationToken);
    }
```

than "Add, Update and Delete" should be really events!? A repository is all about storing/deleting data. 

```
    public interface IRepository<TAggregate> where TAggregate : IAggregate
    {
        Task StoreAsync(TAggregate aggregate, CancellationToken cancellationToken);

        Task ArchiveAsync(TAggregate aggregate, CancellationToken cancellationToken);
        
        Task<TAggregate?> Load(Guid id, int? version, CancellationToken cancellationToken);
    }

```
Store and Archive should store and publish uncommited events.

```
  public class MartenRepository<TAggregate> : IRepository<TAggregate> where TAggregate : class, IAggregate
    {
        private readonly ITransactionBoundary _transactionBoundary;
        private readonly IDocumentStore _store;
        private readonly IEventBus _eventBus;

        public MartenRepository(
            ITransactionBoundary transactionBoundary,
            IDocumentStore store,
            IEventBus eventBus
        )
        {
            _transactionBoundary = transactionBoundary ?? throw new ArgumentNullException(nameof(transactionBoundary));
            _store = store ?? throw new ArgumentNullException(nameof(store));
            _eventBus = eventBus ?? throw new ArgumentNullException(nameof(eventBus));
        }

        public async Task StoreAsync(TAggregate aggregate, CancellationToken cancellationToken)
        {
            var transaction = await GetActiveOrBeginNewTransactionAsync(cancellationToken);

            using (var session = _store.OpenSession(SessionOptions.ForTransaction(transaction)))
            {
                try
                {
                    var events = aggregate.DequeueUncommittedEvents();
                    session.Events.Append(
                        aggregate.Id,
                        events
                    );
                    await session.SaveChangesAsync(cancellationToken);
                    await _eventBus.PublishAsync(events);
                }
                catch
                {
                    await _transactionBoundary.RollbackAsync(cancellationToken);
                    throw;
                }
            }
        }

        public async Task ArchiveAsync(TAggregate aggregate, CancellationToken cancellationToken)
        {
            var transaction = await GetActiveOrBeginNewTransactionAsync(cancellationToken);

            using (var session = _store.OpenSession(SessionOptions.ForTransaction(transaction)))
            {
                try
                {
                    var events = aggregate.DequeueUncommittedEvents();
                    session.Events.Append(
                        aggregate.Id,
                        events
                    );

                    session.Events.ArchiveStream(aggregate.Id);
                    await _eventBus.PublishAsync(events);
                }
                catch
                {
                    await _transactionBoundary.RollbackAsync(cancellationToken);
                    throw;
                }
            }
        }

        public async Task<TAggregate?> Load(Guid id, int? version, CancellationToken cancellationToken)
        {
            await using var session = _store.LightweightSession();
            var aggregate = await session.Events.AggregateStreamAsync<TAggregate>(id, token: cancellationToken);
            return aggregate ?? throw new AggregateNotFoundException(nameof(TAggregate), id);
        }

        private async Task<NpgsqlTransaction> GetActiveOrBeginNewTransactionAsync(CancellationToken cancellationToken)
        {
            var transaction = await _transactionBoundary.GetActiveOrBeginNewTransactionAsync(
                null,
                null,
                cancellationToken
            );
            return transaction;
        }
    }
```

While ITransactionBoundary is

```
public class TransactionBoundary: ITransactionBoundary, IDisposable
    {
        private const IsolationLevel DefaultIsolationLevel = IsolationLevel.ReadCommitted;
        
        private readonly ITenancy _tenancy;
        private NpgsqlConnection? _connection;
        private NpgsqlTransaction? _transaction;

        public TransactionBoundary(ITenancy tenancy)
        {
            _tenancy = tenancy ?? throw new ArgumentNullException(nameof(tenancy));
        }
        
        public NpgsqlTransaction GetActiveOrBeginNewTransaction(IsolationLevel? isolationLevel, string? tenantId = null)
        {
            if (_transaction != null)
            {
                return _transaction;
            }
            
            var tenant = tenantId == null
                ? _tenancy.Default
                : _tenancy[tenantId];

            _connection ??= tenant.CreateConnection();
            _connection.Open();
            _transaction = _connection.BeginTransaction(isolationLevel ?? DefaultIsolationLevel);
            return _transaction;
        }
        
        public async Task<NpgsqlTransaction> GetActiveOrBeginNewTransactionAsync(IsolationLevel? isolationLevel, string? tenantId = null, CancellationToken cancellationToken = default)
        {
            if (_transaction != null)
            {
                return _transaction;
            }
            
            var tenant = tenantId == null
                ? _tenancy.Default
                : _tenancy[tenantId];

            _connection ??= tenant.CreateConnection();
            await _connection.OpenAsync(cancellationToken);
            _transaction = await _connection.BeginTransactionAsync(isolationLevel ?? DefaultIsolationLevel, cancellationToken);
            return _transaction;
        }

        public void Commit()
        {
            ValidatedTransactionIsCreated();
            CommitInternal();
        }

        private void CommitInternal()
        {
            _transaction?.Commit();
            _transaction = null;
        }
        
        public async Task CommitAsync(CancellationToken cancellationToken = default)
        {
            ValidatedTransactionIsCreated();
            await _transaction!.CommitAsync(cancellationToken);
            _transaction = null;
        }

        public void Rollback()
        {
            ValidatedTransactionIsCreated();
            _transaction!.Rollback();
            _transaction = null;
        }
        
        public async Task RollbackAsync(CancellationToken cancellationToken = default)
        {
            ValidatedTransactionIsCreated();
            await _transaction!.RollbackAsync(cancellationToken);
            _transaction = null;
        }

        private void ValidatedTransactionIsCreated()
        {
            if (_transaction == null)
            {
                throw new InvalidOperationException("No Transaction is created. Call BeginTransaction(Async) first.");
            }
        }

        public void Dispose()
        {
            CommitInternal();
            _connection?.Dispose();
            _connection = null;
        }
    }

```

**Comment by oskardudycz** [comment]
@soernt, regarding redundancy for the Add, Update, Delete, that's correct. I intentionally put them as different methods to highlight that in Event Sourcing, all of those methods are the same in Event Sourcing in Event Sourcing. It could be made a single method as you suggested. Tho, remember that the repository pattern hides the specifics of storage. Also, you may want to provide different logic for all of those methods. E.g. in the `Add` method, you could call `StartStream` to initiate the stream with stream type and ensure that we're not appending to an existing stream. I think that you're right that I should make that more explicit by adding explanations in README or comments. The repository is also missing optimistic concurrency handling. 

Regarding transaction processing, that's correct. It's missing from the sample. I used here simplified approach, which may be good enough for many scenarios but does not guarantee 100% delivery. For that, you'd either use what you proposed or an outbox pattern.

Of course, what you proposed here is valid, but I think it could be implemented easier with custom inline projection. Then you wouldn't need to maintain your own transactions management, as Marten internally has a transaction unit of work implemented. I'll try to provide a sample for that.

Typically I used an asynchronous outbox pattern. Doing event bus processing inside a transaction is dangerous, as depending on the time of processing and complexity, it can keep transactions long-lived and cause deadlocks. That's why I didn't suggest that approach as the approach to start with. I wrote about the Outbox Pattern longer in my article: https://event-driven.io/en/outbox_inbox_patterns_and_delivery_guarantees_explained/.

p.s. as I mentioned, I'd keep `Archive` method separated from the repository, to not tempt to use it too often and without considerations 😉

**Comment by soernt** [comment]
@oskardudycz Once again, thank you very much for your detailed explanations, very much appreciated!

Regarding to the in/outbox pattern: Instead of using MediatR, I plan to use [Silverback](https://silverback-messaging.net/). I have some experience with that library at my job. So I refactor the Events, Commands and Queries interfaces to use Silverback.

The approch of a custom inline projection sounds interesting, looking forward for the example.

I am very new to the topic event sourcing, still plenty to learn :-)
