### ISSUE TITLE
Error: BuildYourOwnEventStore/  docker-compose up Error Message

### ISSUE THREAD

**Issue by MoneyMikePMZ** [oskardudycz/EventSourcing.NetCore#93]
I am attempting to go through the self paced workshop in Workshops/BuildYourOwnEventStore/. I have gotten to step 12 and am receiving the following error when running the command docker-compose up from C:\repos\EventSourcing.NetCore\Workshops\BuildYourOwnEventStore\docker:

 -Network docker_postgres Error                                                                                                                                                            15.0s
failed to create network docker_postgres: Error response from daemon: plugin "postgres" not found.

I'm fairly new to this and am not sure if it's something I did on my end or not. So far I have been following all the instructions for setting up my environment by downloading and installing everything. Looking forward to resolving this issue to get started.

**Comment by oskardudycz** [comment]
@MoneyMikePMZ, I apologise for the late feedback, but could you try again? I've done some improvements recently around that, and cannot reproduce that on my side. Which operating system are you running?
